name: prolif
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - pandoc
  - pip
  - myst-nb<1.0
  - mdit-py-plugins
  - networkx
  - recommonmark
  - matplotlib
  - seaborn<1.0
  - sphinx==5.3.0
  - sphinx-copybutton
  - tqdm
  - python==3.11.*
  - mdanalysis
  - rdkit
  - dill
  - multiprocess
  - pip:
    - pyvis
    - py3Dmol
    - sphinx-book-theme
