name: prolif
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - pandoc
  - pip
  - python
  - rdkit
  - cython
  - nbsphinx==0.8.7
  - networkx
  - recommonmark
  - seaborn==0.11.0
  - sphinx==4.1.2
  - tqdm
  - pip:
    - pyvis
    - py3Dmol
