name: prolif-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - boost=1.74.0=py39hcd82cac_2
  - boost-cpp=1.74.0=h9359b55_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.16.0=h9f066cc_1006
  - certifi=2020.12.5=py39hf3d152e_0
  - cycler=0.10.0=py_2
  - fontconfig=2.13.1=h7e3eb15_1002
  - freetype=2.10.4=h7ca028e_0
  - gettext=0.19.8.1=h0b5b191_1005
  - icu=67.1=he1b5a44_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py39h081fc7a_0
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.35.1=hed1e6ac_0
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libglib=2.66.3=h1f3bc88_1
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=3_openblas
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=h4f3a223_6
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - matplotlib-base=3.3.3=py39h98787fa_0
  - ncurses=6.2=h58526e2_4
  - numpy=1.19.4=py39h57d35e7_1
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1h=h516909a_0
  - pandas=1.1.5=py39hde0f152_0
  - pcre=8.44=he1b5a44_0
  - pillow=8.0.1=py39h397ff4d_0
  - pip=20.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.20.0=py39h08627d8_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.9.1=hffdb5ce_1_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2020.4=pyhd8ed1ab_0
  - rdkit=2020.09.2=py39h65247da_0
  - readline=8.0=he28a2e2_2
  - reportlab=3.5.56=py39he59360d_0
  - setuptools=49.6.0=py39h079e4ff_2
  - six=1.15.0=pyh9f0ad1d_0
  - sqlalchemy=1.3.20=py39h07f9747_0
  - sqlite=3.34.0=h74cdb3f_0
  - tk=8.6.10=hed695b0_1
  - tornado=6.1=py39hbd71b63_0
  - tzdata=2020d=h516909a_0
  - wheel=0.36.1=pyhd3deb0d_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - alabaster==0.7.12
    - babel==2.9.0
    - biopython==1.78
    - chardet==3.0.4
    - commonmark==0.9.1
    - cython==0.29.21
    - decorator==4.4.2
    - docutils==0.16
    - griddataformats==0.5.0
    - gsd==2.4.0
    - idna==2.10
    - imagesize==1.2.0
    - jinja2==2.11.2
    - joblib==0.17.0
    - markupsafe==1.1.1
    - mmtf-python==1.1.2
    - msgpack==1.0.0
    - networkx==2.5
    - packaging==20.7
    - pygments==2.7.3
    - recommonmark==0.6.0
    - requests==2.25.0
    - scipy==1.5.4
    - snowballstemmer==2.0.0
    - sphinx==3.3.1
    - sphinx-rtd-theme==0.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - tqdm==4.54.1
    - urllib3==1.26.2
